version: '3.8'

services:
  postgres:
    image: postgres
    container_name: weather-postgres
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: weather-etl
    environment:
      DB_USER: weather_user
      DB_PASSWORD: weather_pass
      DB_NAME: weather_db
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

volumes:
  pgdata:
