version: '3.8'

services:
  postgres:
    image: postgres
    container_name: weather-postgres
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
      POSTGRES_HOST: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: weather-etl
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '8080:8080' 

volumes:
  pgdata:
