apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-analytics-platform
  labels:
    app: weather-analytics-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-analytics-platform
  template:
    metadata:
      labels:
        app: weather-analytics-platform
    spec:
      containers:
        - name: weather-analytics-platform
          image: nadavedri01/weather-analytics-platform:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: POSTGRES_HOST
              value: 'your-database-host'
            - name: POSTGRES_USER
              value: 'your-database-user'
            - name: POSTGRES_PASSWORD
              value: 'your-database-password'
