apiVersion: v1
kind: Service
metadata:
  name: weather-analytics-platform
spec:
  selector:
    app: weather-analytics-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
